// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvpjSNFVCuKNUeQwl4uMW085zq38-iejk',
    appId: '1:194165858330:web:469379f853d1c48d38f1a3',
    messagingSenderId: '194165858330',
    projectId: 'flutter-firebase-demo-3c137',
    authDomain: 'flutter-firebase-demo-3c137.firebaseapp.com',
    storageBucket: 'flutter-firebase-demo-3c137.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdcofJXdFbWzjqUNwAwHPUTxT24GmRaos',
    appId: '1:194165858330:android:87032ce9ad5f0f9f38f1a3',
    messagingSenderId: '194165858330',
    projectId: 'flutter-firebase-demo-3c137',
    storageBucket: 'flutter-firebase-demo-3c137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeaCpGlcMjeADDeXwdpLqFoHIGCqXL2-o',
    appId: '1:194165858330:ios:b2c29277ba5f634238f1a3',
    messagingSenderId: '194165858330',
    projectId: 'flutter-firebase-demo-3c137',
    storageBucket: 'flutter-firebase-demo-3c137.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDay1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeaCpGlcMjeADDeXwdpLqFoHIGCqXL2-o',
    appId: '1:194165858330:ios:b2c29277ba5f634238f1a3',
    messagingSenderId: '194165858330',
    projectId: 'flutter-firebase-demo-3c137',
    storageBucket: 'flutter-firebase-demo-3c137.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebaseDay1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvpjSNFVCuKNUeQwl4uMW085zq38-iejk',
    appId: '1:194165858330:web:c5fddf01ca7aa24938f1a3',
    messagingSenderId: '194165858330',
    projectId: 'flutter-firebase-demo-3c137',
    authDomain: 'flutter-firebase-demo-3c137.firebaseapp.com',
    storageBucket: 'flutter-firebase-demo-3c137.firebasestorage.app',
  );
}
